from app.schemas.auth import UserLoginInput, UserRegistrationInput, UserSession
from app.schemas.analysis import (
    AnalysisChecks,
    AnalysisPerformance,
    AnalysisRequest,
    AnalysisResponse,
    DMARCCheckResult,
    DKIMCheckResult,
    DomainRegistrationResult,
    EmailTLSMXResult,
    EmailTLSResult,
    Finding,
    MXCheckResult,
    MXRecord,
    NormalizedTarget,
    Recommendation,
    SPFCheckResult,
    ScoreBreakdown,
    WebsiteTLSResult,
)
from app.schemas.history import (
    AnalysisDiffSummary,
    DomainHistoryResponse,
    HistoryItem,
    SnapshotChangeItem,
)
from app.schemas.health import HealthResponse
from app.schemas.monitoring import (
    AlertEventSummary,
    MonitoredDomainSummary,
    MonitoringDashboardResponse,
    MonitoringDomainCreateInput,
    MonitoringDomainDetailResponse,
    MonitoringRunSummary,
)

__all__ = [
    "AlertEventSummary",
    "AnalysisChecks",
    "AnalysisPerformance",
    "AnalysisDiffSummary",
    "AnalysisRequest",
    "AnalysisResponse",
    "DMARCCheckResult",
    "DKIMCheckResult",
    "DomainRegistrationResult",
    "DomainHistoryResponse",
    "EmailTLSMXResult",
    "EmailTLSResult",
    "Finding",
    "HealthResponse",
    "HistoryItem",
    "MXCheckResult",
    "MXRecord",
    "MonitoredDomainSummary",
    "MonitoringDashboardResponse",
    "MonitoringDomainCreateInput",
    "MonitoringDomainDetailResponse",
    "MonitoringRunSummary",
    "NormalizedTarget",
    "Recommendation",
    "SPFCheckResult",
    "ScoreBreakdown",
    "SnapshotChangeItem",
    "UserLoginInput",
    "UserRegistrationInput",
    "UserSession",
    "WebsiteTLSResult",
]
